apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "deployment.fullname" . }}
data:
  quarkus.datasource.username: {{ .Values.api.configuration.datasource.username }}
  quarkus.datasource.password: {{ .Values.api.configuration.datasource.password }}
type: Opaque